package com.mycompany.biblioteca_digital.views1;
import com.mycompany.biblioteca_digital.servicio.RegistroUsuario;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import com.mycompany.biblioteca_digital.modelo.Persona;
import javax.swing.JOptionPane;
/**
 *
 * @author ALEJANDRO
 */
public class modem extends javax.swing.JPanel {

    /**
     * Creates new form modem
     */
    public modem() {
    initComponents();
    sello1.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sello.png")).getImage().getScaledInstance(120, 170, java.awt.Image.SCALE_SMOOTH)));

// 2. Forzar el centrado horizontal dentro del espacio del Label
    sello1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    imagen7.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono5.png")).getImage().getScaledInstance(100, 80, java.awt.Image.SCALE_SMOOTH)));

// 2. Forzar el centrado horizontal dentro del espacio del Label
    imagen7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    imagen8.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono6.png")).getImage().getScaledInstance(100, 80, java.awt.Image.SCALE_SMOOTH)));

// 2. Forzar el centrado horizontal dentro del espacio del Label
    imagen8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vista = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        sello1 = new javax.swing.JLabel();
        imagen8 = new javax.swing.JLabel();
        imagen7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        vista.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 29)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("BIBLIOTECA VIRTUAL ");

        btnIniciarSesion.setBackground(new java.awt.Color(153, 0, 51));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setBorder(null);
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.addActionListener(this::btnIniciarSesionActionPerformed);

        btnRegistrarse.setBackground(new java.awt.Color(153, 0, 51));
        btnRegistrarse.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setBorder(null);
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarse.addActionListener(this::btnRegistrarseActionPerformed);

        jLabel2.setFont(new java.awt.Font("STZhongsong", 1, 16)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("STZhongsong", 1, 16)); // NOI18N
        jLabel3.setText("Contraseña:");

        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Ingrese su usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);

        txtContraseña.setForeground(new java.awt.Color(204, 204, 204));
        txtContraseña.setText("***********");
        txtContraseña.setBorder(null);
        txtContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContraseñaFocusLost(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(153, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 102));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 102));

        sello1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sello.png"))); // NOI18N

        imagen8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono6.png"))); // NOI18N

        imagen7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono5.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("BIENVENIDO");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 29)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("UET");

        javax.swing.GroupLayout vistaLayout = new javax.swing.GroupLayout(vista);
        vista.setLayout(vistaLayout);
        vistaLayout.setHorizontalGroup(
            vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaLayout.createSequentialGroup()
                .addGroup(vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vistaLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vistaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vistaLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vistaLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(sello1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vistaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vistaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vistaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vistaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3))
                    .addGroup(vistaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vistaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vistaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(imagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(imagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vistaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        vistaLayout.setVerticalGroup(
            vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addComponent(sello1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
                                   
    String usuario = txtUsuario.getText().trim();
    String contraseña = txtContraseña.getText().trim();

    if (usuario.isEmpty() || contraseña.isEmpty()
            || usuario.equals("Ingrese su usuario")
            || contraseña.equals("***********")) {
        JOptionPane.showMessageDialog(this,
            "Por favor complete todos los campos",
            "Campos Vacíos",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    RegistroUsuario registro = com.mycompany.biblioteca_digital.servicio.AppContext.getInstance().getRegistroUsuario();
    Persona persona = registro.login(usuario, contraseña);

    if (persona != null) {
        JOptionPane.showMessageDialog(this,
            "Bienvenido " + persona.getNombre() + " " + persona.getApellido() + "\n" +
            "Tipo: " + persona.getTipo(),
            "Login Exitoso",
        JOptionPane.INFORMATION_MESSAGE);
        
        JOptionPane.showMessageDialog(this,
        "Sesión iniciada correctamente\n\n" +
        "Usuario: " + persona.getNombre() + " " + persona.getApellido() + "\n" +
        "Tipo: " + persona.getTipo(),
        "Bienvenido",
         JOptionPane.INFORMATION_MESSAGE);
          } else {
        JOptionPane.showMessageDialog(this,
            "Usuario o contraseña incorrectos\n\nPor favor verifique sus credenciales.",
            "Error de Autenticación",
            JOptionPane.ERROR_MESSAGE);
        txtContraseña.setText("");
        txtUsuario.requestFocus();
    }

    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
    // Obtener el panel padre (VentanaLoading1)
    java.awt.Container parent = this.getParent();
    
    // Buscar el panel de registro (registroU1)
    for (java.awt.Component comp : parent.getComponents()) {
        if (comp.getName() != null && comp.getName().equals("registroU1")) {
            // Ocultar panel de login
            this.setVisible(false);
            // Mostrar panel de registro
            comp.setVisible(true);
            return;
        }
    }
    
   

        ShowJPanel(new registroU1());
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        // TODO add your handling code here:
        if (txtUsuario.getText().equals("Ingrese su usuario")) {
    txtUsuario.setText("");
    txtUsuario.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_txtUsuarioFocusGained
    }
    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        // TODO add your handling code here:
        if (txtUsuario.getText().isEmpty()) {
    txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
    txtUsuario.setText("Ingrese su usuario");
    }//GEN-LAST:event_txtUsuarioFocusLost
    }
    private void txtContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseñaFocusGained
        // TODO add your handling code here:
          if (txtContraseña.getText().equals("***********")) {
    txtContraseña.setText("");
    txtContraseña.setForeground(java.awt.Color.BLACK);
    } 
    }//GEN-LAST:event_txtContraseñaFocusGained

    private void txtContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseñaFocusLost
        // TODO add your handling code here:
        if (txtContraseña.getText().isEmpty()) {
    txtContraseña.setForeground(new java.awt.Color(153, 153, 153));
    txtContraseña.setText("***********");
    }//GEN-LAST:event_txtContraseñaFocusLost
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel imagen7;
    private javax.swing.JLabel imagen8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel sello1;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JPanel vista;
    // End of variables declaration//GEN-END:variables

    private void ShowJPanel(JPanel v1){
        v1.setSize(420,710);
        v1.setLocation(0,0);
        
        vista.removeAll();
        vista.add(v1,BorderLayout.CENTER);
        vista.revalidate();
        vista.repaint();
    }
}
